import { useState } from 'react';
import './ScoreSummary.css';

const ScoreSummary = ({ listeningRaw, readingRaw, scaledScores }) => {
  const [copied, setCopied] = useState(false);

  const handleCopyScore = () => {
    const textToCopy = `My TOEIC Score:\nListening: ${scaledScores.listening} (Raw: ${listeningRaw}/100)\nReading: ${scaledScores.reading} (Raw: ${readingRaw}/100)\nTotal: ${scaledScores.total}/990\n\nGenerated by TOEIC Point Counter`;
    navigator.clipboard.writeText(textToCopy).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="score-summary-container glass-panel">
      <h2 className="summary-title text-gradient">Your Score</h2>
      
      <div className="scores-grid">
        <div className="score-card listening-card">
          <h3 className="score-label">Listening</h3>
          <div className="raw-score">{listeningRaw} / 100</div>
          <div className="scaled-score text-gradient">{scaledScores.listening}</div>
        </div>

        <div className="score-card reading-card">
          <h3 className="score-label">Reading</h3>
          <div className="raw-score">{readingRaw} / 100</div>
          <div className="scaled-score text-gradient">{scaledScores.reading}</div>
        </div>
      </div>

      <div className="total-score-card glass-panel">
        <h3 className="total-label">Total TOEIC Score</h3>
        <div className="total-score text-gradient">
          {scaledScores.total}
        </div>
      </div>

      <button 
        className="btn copy-score-btn" 
        onClick={handleCopyScore}
        aria-label="Copy Score to Clipboard"
      >
        {copied ? '✓ Copied!' : '📋 Copy Score'}
      </button>
    </div>
  );
};

export default ScoreSummary;
